### ISSUE TITLE
błąd podczas obsługi pliku

### ISSUE THREAD

**Issue by mkjasinski** [chesteroni/nmass#4]
Po wywołaniu polecenia:
`python nmass.py --inmass=./test.xml`

Otrzymuję błąd:

```
Found saved state, resuming
Traceback (most recent call last):
  File "nmass.py", line 119, in <module>
    sectest()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "nmass.py", line 54, in sectest
    if state_content[4] == "<stdin>":
IndexError: list index out of range
```

W razie wyjątku w obsłudze pliku stanu powinien być on ignorowany.

**Comment by chesteroni** [comment]
Fixed with https://github.com/chesteroni/nmass/commit/05ae676c7df2d06324a4a47d08af19faafd65bfb
